version: '3.9'
services:
  for_music_database:
    image: 'postgres:15'
    container_name: for_music_database
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'for_music_database:/var/lib/postgresql/data'
    networks:
      - for_music_network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}"
        ]
      retries: 3
      timeout: 5s
    mem_limit: 500m
networks:
  for_music_network:
    driver: bridge
volumes:
  for_music_database:
    driver: local
